### ISSUE TITLE
Saved model

### ISSUE THREAD

**Issue by WangChen100** [leeyegy/TokenPose#4]
Hi, I'm very interested in your work. Can you provide the saved model through Google drive or Baidu pan?

**Comment by leeyegy** [comment]
Sorry for the  late reply. And thank you for your attention. 

Because the code has been reconstructed, the previous pretrained model cannot be loaded directly, so it has not been released for the time being. Later, when I am free, I will convert the pretrained model and adapt it to the current code for open source. 

However, I believe that based on the current code, it is also easy to carry out reproduction experiments.
